import { Module } from '@nestjs/common';

import { InfraModule } from '@infra/infra.module';
import {
  AssignTechnicianUseCase,
  CreateServiceCategoryUseCase,
  CreateCustomerAddressUseCase,
  CreateServiceRequestUseCase,
  CreateServiceTypeUseCase,
  CreateTechnicianUseCase,
  CreateTechnicianAvailabilityWindowUseCase,
  GetCurrentUserUseCase,
  GetDispatcherQueueUseCase,
  GetEligibleTechniciansUseCase,
  GetServiceRequestUseCase,
  GetTechnicianCalendarUseCase,
  ListCustomerAddressesUseCase,
  ListServiceCategoriesUseCase,
  ListServiceAreasUseCase,
  ListServiceTypesUseCase,
  ListTechniciansUseCase,
  LoginUseCase,
  RefreshSessionUseCase,
  RegisterCustomerUseCase,
  SearchServiceRequestsUseCase,
  TriageServiceRequestUseCase,
  UpdateServiceCategoryUseCase,
  UpdateCustomerAddressUseCase,
  UpdateServiceTypeUseCase,
  UpdateTechnicianUseCase,
} from '@application/use-cases';

const useCases = [
  AssignTechnicianUseCase,
  RegisterCustomerUseCase,
  LoginUseCase,
  RefreshSessionUseCase,
  GetCurrentUserUseCase,
  GetDispatcherQueueUseCase,
  GetEligibleTechniciansUseCase,
  ListServiceCategoriesUseCase,
  ListServiceTypesUseCase,
  ListServiceAreasUseCase,
  CreateCustomerAddressUseCase,
  ListCustomerAddressesUseCase,
  UpdateCustomerAddressUseCase,
  CreateServiceCategoryUseCase,
  UpdateServiceCategoryUseCase,
  CreateServiceTypeUseCase,
  UpdateServiceTypeUseCase,
  CreateTechnicianUseCase,
  CreateTechnicianAvailabilityWindowUseCase,
  UpdateTechnicianUseCase,
  ListTechniciansUseCase,
  GetTechnicianCalendarUseCase,
  CreateServiceRequestUseCase,
  SearchServiceRequestsUseCase,
  GetServiceRequestUseCase,
  TriageServiceRequestUseCase,
];

@Module({
  imports: [InfraModule],
  providers: useCases,
  exports: useCases,
})
export class UseCasesModule {}
